global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'trader-v4'
    static_configs:
      - targets: ['trader:8080']
        labels:
          group: 'trading-bot'
  
  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:5000']
        labels:
          group: 'web-dashboard'
  
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          group: 'database'
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          group: 'cache'